name: Node.js CI - with no cache

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: 'npm'
      - name: run build
        run: npm ci
      - run: npm run build --if-present
